### <h3 style="color: #ADD8E6;">Complementaria 2: Álgebra Lineal en Python</h3>

El objetivo de esta complementaria es aprender a definir y manejar matrices en Python. El uso de matrices aplicado a la construcción de Cadenas de Markov también será tratado a lo largo de la complementaria.

<h3 style="color: #ADD8E6;">Manejo de matrices
</h3>

Para crear y realizar operaciones sobre matrices en Python utilzaremos la libreria `numpy` que se abrevia como `np`.

In [1]:
import numpy as np

Existen diferentes formas para crear matrices en Python. Aqui hay algunos ejemplos: 

1. Se puede crear una matriz a partir de varias listas:

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. Se puede crear una matriz llena de ceros (esta forma de crear la matriz será de suma utilidad cuando estemos definiendo las cadenas de Markov):

In [3]:
matrix2 = np.zeros((3, 3))  # Matriz 3x3 de ceros
print(matrix2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Crear una matriz identidad (útil para realizar análisis de tiempos)

In [4]:
matrix3 = np.eye(4)  # Matriz identidad 4x4
print(matrix3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Para acceder a un elemento de una matriz se deben utilizar los índices del respectivo elemento. Se debe tener cuidado ya que los índices en Python empiezan en 0, tal que si, por ejemplo, se quiere acceder a la fila `1` se debe utilizar el `0`. 

In [5]:
# Accede al elemento en la fila 1, columna 2
elemento = matrix[0, 1]
elemento

2

También se puede extraer filas o columnas de la siguiente manera:

In [6]:
# Extraer la primera fila de 'matrix'.
fila1 = matrix[0,:]
fila1

array([1, 2, 3])

In [7]:
# Extraer la tercera columna de 'matrix'.
columna2 = matrix[:,2]
columna2

array([3, 6, 9])

De igual manera se pueden agregar filas o columnas con la función `append`. Si se quiere aregar una nueva fila el parámetro `axis` de la funcion `append` debe ser igual a `0`; si se quiere agregar una nueva columna, `axis` debe ser igual a `1`.

In [8]:
# Nueva fila que se quiere agregar.
nueva_fila = np.array([10,11,12])

# Agregar la nueva fila a la matriz
matrix_con_fila = np.append(matrix, [nueva_fila], axis = 0)
matrix_con_fila

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# Nueva columna que se quiere agregar.
nueva_columna = np.array([[13], [14], [15]])

# Agregar la nueva columna a la matriz
matrix_con_columna = np.append(matrix, nueva_columna, axis = 1)
matrix_con_columna

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15]])

<h3 style="color: #ADD8E6;">Operaciones matriciales
</h3>

A modo de ejemplo, se crearán dos matrices llenas de números aleatorios que siguen una distribución normal generados por el comando `random.normal` de la libreria numpy, que tiene como parámetros la media, la desviación estandar y el tamaño de la matriz 

In [10]:
A = np.random.normal(loc = 20, scale = 8, size = (6,6))
print(A)

[[25.81265713 24.85613895 28.70628961 19.44588963 20.90783179 14.08777945]
 [23.84263572 22.67036504 15.93272035 29.44478882 20.00088753 22.09278642]
 [22.86086204 18.93739172 21.26575341 20.47844934 17.11513131  9.53528466]
 [19.62412285 12.45229694  3.2575555  16.41431898 12.37062484 22.78315285]
 [ 9.28321329 22.62591235 21.88950667 24.25665514 19.11453088 21.83657415]
 [22.2610462   8.71932848 18.78780849 21.84789129 33.43497213 21.35365735]]


In [11]:
B = np.random.normal(loc = 10, scale = 3, size = (6,6))
print(B)

[[ 6.89920104  5.90193982  9.07522923 11.50778604 13.35897988  7.78702411]
 [ 9.20474693  4.49378974  9.46107463  8.99757115 10.09333782  5.56664408]
 [ 8.68566551  5.31513192 13.09481156  9.51212595 10.82691885 10.97862958]
 [11.6094933   9.09613595 11.04861413 15.12728433  7.83658696  4.94660296]
 [11.46153686 15.26870219 14.60802194 11.54520683 11.45896756  6.94930574]
 [ 5.35432243  8.96600976 14.94826888 10.81870454 10.7268584   8.42466913]]


A continuación, se encuentran algunos comandos de interes que nos permiten realizar operaciones matriciales en Python

| Comando | Explicación |
|:---:|:---:|
| `A.T` | Transpuesta de la matriz A |
| `A + B` | Suma elemento a elemento de las matrices A y B |
| `A - B` | Resta elemento a elemento de las matrices A y B |
| `A @ B` | Producto matricial de A por B |
| `A * B` | Producto elemento a elemento de A por B |
| `np.linalg.det(A)` | Calcula el determinante de la matriz cuadrada A |
| `np.linalg.inv(A)` | Calcula la inversa de la matriz cuadrada A |
| `np.linalg.solve(A, b)` | Resuelve el sistema de ecuaciones lineales Ax = b |
| `np.linalg.eig(A)` | Calcula los valores y vectores propios de la matriz cuadrada A |
| `np.diag(A)` | Extrae la diagonal principal de la matriz A como un vector |
| `A.sum(axis = 1)` | Calcula la suma de los elementos de cada fila de la matriz A |


<h3 style="color: #ADD8E6;">Cadenas de Markov</h3>

El uso de matrices sirve para definir la representación de una cadena de Markov en Python. Por ejemplo, en las cadenas continuas es posible definir la matriz generadora (o de tasas de transición) **Q**, y en las discretas se define la matriz de probabilidades de transición a un paso **P**. En Python se utilizará la libreria `jmarkov`.

>**¡Ponte a prueba!**.
>Modela la evolución del Índice de calidad del aire (ICA) como una cadena de Markov.

En primer lugar, se modela la situación como una cadena de Markov de tiempo discreto. Se define la variable de estado y el espacio de estados correspondiente.

$$
I_n = \text{Nivel del ICA en el n-ésimo día}
$$

$$
S_I = \{1, 2, 3, 4, 5\}
$$


Es importante considerar que, en el espacio de estados, los niveles de calidad del aire aparecen en orden creciente de empeoramiento: el estado 1 corresponde a la clase Buena y el estado 5 a Muy dañina para la salud.

Como es una cadena de Markov en tiempo discreto (CMTD) se debe definir la matriz P. Las probabilidades de transición en un paso entre estados de la cadena de Markov discreta son las siguientes:

$$
P_{i \rightarrow j} = \begin{cases}
0.5 & \text{si } j = i + 1, i < 5 \\
0.3 & \text{si } j = i, 1 < i < 5 \\
0.2 & \text{si } j = i - 1, i > 1 \\
0.5 & \text{si } j = i = 1 \\
0.8 & \text{si } j = i = 5 \\
0 & \text{dlc}
\end{cases}
$$


Para crear matrices en Python, utilizaremos la biblioteca `numpy`, que se emplea para trabajar con matrices y realizar cálculos numéricos de manera eficiente. Esta biblioteca se abrevia comúnmente como `np`.

In [12]:
# Importar las librerias necesarias.

import numpy as np

A continuación, se implementa esta CMTD en Python. Se empieza creando la matriz de probabilidades de transición que se llamará `matriz`:

In [13]:
filas = 5
columnas = 5

# Crear una matriz de ceros de 5x5
matriz = np.zeros((filas, columnas), dtype = float)

Ahora, se recorren las filas y columnas de la matriz para llenarla de acuerdo a la formulación general definida previamente.

In [14]:
# Llenar la matriz con valores
for i in range(filas):
    for j in range(columnas):
        if j == i + 1 and i < filas - 1:
            matriz[i, j] = 0.5
        elif j == i and i > 0 and i < filas - 1:
            matriz[i, j] = 0.3
        elif j == i - 1 and i > 0:
            matriz[i, j] = 0.2
        elif i == j == 0:
            matriz[i, j] = 0.5
        elif i == j == filas - 1:
            matriz[i, j] = 0.8

print(matriz)

# Verificación de que las filas de la matriz suman 1.
matriz.sum(axis = 1)


[[0.5 0.5 0.  0.  0. ]
 [0.2 0.3 0.5 0.  0. ]
 [0.  0.2 0.3 0.5 0. ]
 [0.  0.  0.2 0.3 0.5]
 [0.  0.  0.  0.2 0.8]]


array([1., 1., 1., 1., 1.])